# Generated by Django 4.2.3 on 2023-07-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwear_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
    ]
