# Generated by Django 4.2.3 on 2023-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear_user', '0002_remove_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
