# Generated by Django 4.2.3 on 2023-08-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear_user', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category_female',
            field=models.CharField(choices=[('Heels', 'Heels'), ('Ballet flats', 'Ballet flats'), ('Court shoe', 'Court shoe'), ('Platform shoe', 'Platform shoe'), ('Wedge', 'Wedge'), ('Other', 'Other')], default='female_shoes', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category_male',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Loafer', 'Loafer'), ('Chelsea boot', 'Chelsea boot'), ('Moccasins', 'Moccasins'), ('Walking Shoes', 'Walking Shoes'), ('Other', 'Other')], default='male_shoes', max_length=200),
        ),
    ]
