# Generated by Django 4.2.3 on 2023-08-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear_user', '0006_remove_product_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category_female',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category_male',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200),
        ),
    ]
