# Generated by Django 4.2.3 on 2023-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear_user', '0007_remove_product_product_category_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_access',
            field=models.BooleanField(default=True),
        ),
    ]
