# Generated by Django 4.2.3 on 2023-08-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwear_user', '0008_user_admin_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_access',
            field=models.BooleanField(default=False),
        ),
    ]
