# Generated by Django 4.2.3 on 2023-08-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footwear_user', '0009_alter_user_admin_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footwear_user.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footwear_user.user')),
            ],
        ),
    ]
